name: JS Commons Tests
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - lts/*
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run docs
      - run: npm run test
      - run: npm run test_node